### ISSUE TITLE
Add hotkeys

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/electron_player#5]
Make it possible to move frame by frame (when paused). Send the current time to the console.

While playing, make <kbd><-</kbd> and <kbd>-></kbd> skip 5 seconds.

Make spacebar toggle `play` and `pause`.

Maybe the best thing to do, is to implement all of YouTube's hotkeys, kind of like [this](https://github.com/AjaxGb/Better-Chrome-Native-Video)

**Comment by konnorjp** [comment]
Commit 4599758 added hotkeys: space for play/pause and left and right arrows for moving frame by frame by 0.1 seconds when paused and skipping 5 seconds when playing.

Is 0.1 seconds a small enough step for the frame by frame step? Or should it be smaller?

**Comment by reynoldsnlp** [comment]
0.1 seconds is probably just right.

**Comment by konnorjp** [comment]
Okay. My code for the hotkeys works perfectly, but there is a default behavior that I can't seem to get around. The html5 video player has similar hotkeys: space and left and right arrows. The default arrow events seek the video forward or backward about 1.5 seconds when paused. The default events fire before the events that I created. There are two ways that I can currently see to overcome this behavior. 

The first would be to hide the html5 video controls, and create our own controls. The default behavior is tied to the visibility of the controls, so if we hide them, the default events will not be active. I think that there is some code to define our own controls on stack overflow. 

The second way would be to keep more accurate record of the currentTime of the video with the variable player.current_time. Then we would be able to compare the player.current_time with the video.currentTime. After the video is paused, we update player.current_time and then when the arrows are pressed, we compare player.current_time with video.currentTime. If the difference is greater than .1 seconds then we manually change the video.currentTime to be player.current_time + .1. I need to make sure that if someone clicks on the player to skip to a specific time while paused that I update player.current_time (maybe I make have it check not only for a difference greater than .1 seconds, but also less than 2 seconds: this would only work if we expected the user to only click more than 2 seconds away).

I'm going to start implementing the second option because it seems simpler.

**Comment by konnorjp** [comment]
Another interesting thing about the default behavior is that if I interact with the console in the dev tools, the default behavior disappears and the player works as I want it to.

I think that though the second option makes sense, it may be more difficult that we want it to be. I am running into a problem that the default spacebar pause/play event is interfering with the one that I defined, but when I remove my listener for the spacebar, the default behavior doesn't start until after I manually pause the video. I think that we would have to pretty much keep track of the entire state of the video element inside of our player object in order to implement the second option (which we would have to do anyways if we were to define our own controls for the video player).
