### ISSUE TITLE
Add annotation mode, in which censor <div> is selectable, draggable, resizable.

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/electron_player#6]
Add flag at launch to enable `annotation mode`. Something like `$ electron app.js annotate` and maybe with the alias `$ electron app.js a` for short. Open the app with developer tools open at the bottom of the window.

On hover, show censor div position attributes.

In this mode, censor divs are [resizable](https://www.w3schools.com/cssref/css3_pr_resize.asp) and draggable.

**Comment by konnorjp** [comment]
Add toggle for annotation mode on first page

**Comment by konnorjp** [comment]
Commits:
95a68bc : changed file layout to accommodate command line arguments "a", "-a" and "annotate" which open up the annotation mode, censor divs change color on hover
94c8796 : added annotation mode toggle from home screen, made toggle function more consistent and comprehensive
7b4d4ee : added jquery and jquery-ui to make censor divs resizable and draggable, changed call to annotationMode toggle in renderer
10c0bf8 : added tooltip to censor divs to display width and height, censor divs are now resizable and draggable
605534d : automatic updating of annotation object's censor divs' positions with resizing

Should the updated censor annotations be saved to the JSON file when the user exits the player? It should probably be automatic or maybe we can have it be a manual button like Reload JSON filters: "Save JSON filters".

Also, when resizing or dragging the censor, should we make that change last for a couple seconds after it's made? This would make it so that the censor doesn't instantly pop back to the previous size or position at the next time step, which would potentially make editing a bit easier.

**Comment by reynoldsnlp** [comment]
Saving the json file again could be difficult because moving censors have more complicated annotations to manage. As far as I'm concerned, updated the numbers in the json file manually is not too hard.

Don't worry about making the censor stay in position. The most likely use case is resizing and dragging *while the film is paused*, so the javascript doesn't update the position back to the original position.
