### ISSUE TITLE
Add button to `reload filters json`

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/electron_player#7]
Add a button in the top right corner called `Reload filters json`, that is visible whenever the `< Return to Menu` button is visible. When clicked, reload the filters from the json file. This makes it possible to see changes in the json file without closing and reopening all the files, losing your current position, etc.

**Comment by reynoldsnlp** [comment]
This button could be visible only in annotation mode, c.f. #6.

**Comment by konnorjp** [comment]
The following are commits that solve this issue.
95a68bc : added reload JSON Button, which only appears in annotation mode
85f084b : Correctly reloads JSON
7b4d4ee : reload button toggle is corrected so that it disappears on the splash screen
4599758 : Final changes to reload button so that it doesn't show when it's not annotation mode
